Expand base model
brookite/VSTU_ScheduleAPI pull request #2
Opened 2024-11-25 10:19 UTC by pol1waew

Added new model classes

2024-11-25 10:25 UTC, brookite commented
Сейчас уже заметил проблему с наименованием классов: organization, department не соответствует стилю PEP8, классы должны называться с большой буквы, наряду с другими моделями

2024-11-25 10:29 UTC, brookite commented
Не совсем понял, зачем в department ссылка на другой department. Следует также подумать о целесообразности EventPlace в текущих условиях, если появляется модель учреждения, возможно следует связать их с building для логичности. Нужно обсудить это с руководителем

2024-11-25 12:17 UTC, den1s0v commented
1. `organization` → `Organization`
2. `Organization.schedule` убрать, переместить в `AbstractSchedule.organization` (при связи `1 — *` поле внешнего ключа прописывается на стороне `*`)
3. `department` → `Department`
4. `Department.department` → `Department.parent_department` (м.б. `NULL`)
5. `str(self.name) + f" ({self.role})"` → `f"{self.name} ({self.role})"`
6. `Event` разделить на `Event` и `AbstractEvent`:
  - `AbstractEvent` связан с абстрактным расписанием, всем смысловым, что в `Event`, и `place` и `time_slot` из `EventHolding`, но `абстрактный день` вместо даты.
  - `Event` ссылается на `AbstractEvent` как на шаблон, и на множество `EventHolding` (в последнем место и время может быть переопределено по сравнению с `AbstractEvent`)

2024-11-25 12:18 UTC, den1s0v commented
(После исправлений — push коммиты в ту же ветку, и PR обновится автоматически)

2024-11-25 16:53 UTC, den1s0v commented
Детально по переработке модели:
- ранее роль шаблона и конкретного занятия выполняли сущности `Event `и `EventHolding`, соответственно. И, если честно, суть (и название) последней мне не очень нравилась.
- Теперь шаблон переехал в `AbstractEvent`, и необходимость в "промежуточном шаблоне" отпала.
- `EventHolding` упраздняем, его роль передаётся модели Event. 
- `AbstractEvent` заключает в себя полные данные, которые содержатся в ячейке расписание из Excel таблицы (предмет, тип занятия, время дня и участники), кроме собственно календарных дат, вместо этого назначается на абстрактный день (абстрактного расписания).
- Event ссылается на `AbstractEvent` как на шаблон, НО: место, время и состав участников **_могут_** быть точечно переопределены по сравнению с `AbstractEvent` — например, разовая замена или перенос занятий. В обычном состоянии (при отсутствии любых переопределений) все эти дополнительные поля установлены в `NULL`.

Итог:
del `EventHolding` .

`AbstractEvent`:
 - subject
 - kind
 - participants
 - place 
 - time_slot 
 - abstract_day  # Через абстрактный день есть связь с абстрактным расписанием

`Event`:
 - abstract_event
 - date  # собственно день проведения (NOT NULL)
 - schedule
 - subject_override  (may be NULL)
 - kind_override  (may be NULL)
 - participants_override  (may be NULL)
 - place_override  (may be NULL)
 - time_slot_override  (may be NULL)

Добавить в `Schedule`:
 - `status`: int — enum: Активно = 0 / Отключено = 1 / Будущее = 2 / Архивное = 3

2024-11-25 17:04 UTC, den1s0v requested changes
(Нужны правки по комментарию выше)

2024-12-04 15:19 UTC, den1s0v requested changes
небольшая правка, а в целом выглядит нормально.

2024-12-04 15:19 UTC, den1s0v commented on api/models.py
> +        verbose_name="Подразделение"
"Родительское подразделение"

2025-02-21 17:54 UTC, merged